### ISSUE TITLE
Will the video features be released?

### ISSUE THREAD

**Issue by Zhang-Each** [Kuaipedia/Kuaipedia#1]
Nice work! 
I found that the released information of the video is the caption, asr of each video.
I want to know whether the raw video or video features will be released of the subset.

**Comment by ScarletPan** [comment]
Hi thanks, the raw video can be found by concatenating `video_id` with the prefix https://www.kuaishou.com/short-video/. 

E.g. https://www.kuaishou.com/short-video/3xwwuqndapzs6nu

**Comment by Zhang-Each** [comment]
Can we batch download these videos by a python script?

**Comment by ScarletPan** [comment]
Yea, take a try
